name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.4.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies with poetry
        run: poetry install
      - name: Pytest with code coverage
        run: poetry run pytest --cov --cov-report=term --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: htmlcov
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
